/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hadoopguı;

import java.awt.Dimension;
import java.awt.FileDialog;
import java.awt.Frame;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Ali_Asaf
 */
public class AnaEkran extends javax.swing.JFrame {
    String file_tam_path;
    /**
     * Creates new form AnaEkran
     */
    public AnaEkran() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        jButtonSonuc.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel_AnaEkran = new javax.swing.JPanel();
        btnDosyaSec = new javax.swing.JButton();
        jComboBox_fonksiyonlar = new javax.swing.JComboBox();
        jlabel_FonksiyonSec = new javax.swing.JLabel();
        jlabel_secilen_dosya_adi = new javax.swing.JLabel();
        jButtonBaslat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jButtonSonuc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jpanel_AnaEkran.setOpaque(false);

        btnDosyaSec.setLabel("Dosya Seç");
        btnDosyaSec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDosyaSecMouseClicked(evt);
            }
        });
        btnDosyaSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosyaSecActionPerformed(evt);
            }
        });

        jComboBox_fonksiyonlar.setMaximumRowCount(5);
        jComboBox_fonksiyonlar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mean", "Summation", "Standart Dev.", "Min-Max-Range", "Median" }));

        jlabel_FonksiyonSec.setText("Fonksiyon Seç :");

        jlabel_secilen_dosya_adi.setText("Dosya Seçilmedi");

        jButtonBaslat.setText("Başlat");
        jButtonBaslat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBaslatMouseClicked(evt);
            }
        });

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jScrollPane1.setViewportView(jTextAreaLog);

        jButtonSonuc.setText("Sonuçlar");
        jButtonSonuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSonucMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Jpanel_AnaEkranLayout = new javax.swing.GroupLayout(Jpanel_AnaEkran);
        Jpanel_AnaEkran.setLayout(Jpanel_AnaEkranLayout);
        Jpanel_AnaEkranLayout.setHorizontalGroup(
            Jpanel_AnaEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_AnaEkranLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(Jpanel_AnaEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonBaslat)
                    .addGroup(Jpanel_AnaEkranLayout.createSequentialGroup()
                        .addGroup(Jpanel_AnaEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_AnaEkranLayout.createSequentialGroup()
                                .addComponent(btnDosyaSec)
                                .addGap(54, 54, 54))
                            .addGroup(Jpanel_AnaEkranLayout.createSequentialGroup()
                                .addGroup(Jpanel_AnaEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonSonuc)
                                    .addComponent(jlabel_FonksiyonSec))
                                .addGap(55, 55, 55)))
                        .addGroup(Jpanel_AnaEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_fonksiyonlar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel_secilen_dosya_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_AnaEkranLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Jpanel_AnaEkranLayout.setVerticalGroup(
            Jpanel_AnaEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_AnaEkranLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(Jpanel_AnaEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDosyaSec)
                    .addComponent(jlabel_secilen_dosya_adi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Jpanel_AnaEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_fonksiyonlar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_FonksiyonSec))
                .addGap(21, 21, 21)
                .addGroup(Jpanel_AnaEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBaslat)
                    .addComponent(jButtonSonuc))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Jpanel_AnaEkran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel_AnaEkran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDosyaSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosyaSecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDosyaSecActionPerformed

    private void btnDosyaSecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDosyaSecMouseClicked
        // TODO add your handling code here:
        
        FileDialog dialog = new FileDialog((Frame)null, "Select File to Open");
        dialog.setMode(FileDialog.LOAD);
        dialog.setVisible(true);
        String file = dialog.getFile();
        if(file!=null)
            jlabel_secilen_dosya_adi.setText(file);
        
        file_tam_path = dialog.getDirectory()+dialog.getFile();
            
        //System.out.print(file_tam_path);
    }//GEN-LAST:event_btnDosyaSecMouseClicked

    private void jButtonBaslatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBaslatMouseClicked
        // TODO add your handling code here:
        String func = jComboBox_fonksiyonlar.getSelectedItem().toString();
        System.out.println(func);
        
        // Bu şekilde fonksiyonların seçildiğini kontrol edebiliyoruz.
        if(func=="Mean")
            System.out.println("Mean Secildi");
        
        
        if(file_tam_path==null)
            //System.out.println("Dosya Seçilmedi.");
            JOptionPane.showMessageDialog(null, "Dosya Seçilmedi");
        else{
            System.out.println(file_tam_path);
            jButtonSonuc.setEnabled(true);
            // Bu kısımda gerekli hadoop kodlarını çalıştıracağız.
        }
        jTextAreaLog.append("A ha\n");
        
    }//GEN-LAST:event_jButtonBaslatMouseClicked

    private void jButtonSonucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSonucMouseClicked
        // TODO add your handling code here:
        System.out.println("Sonuçlara Tıklandı.");
    }//GEN-LAST:event_jButtonSonucMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel_AnaEkran;
    private javax.swing.JButton btnDosyaSec;
    private javax.swing.JButton jButtonBaslat;
    private javax.swing.JButton jButtonSonuc;
    private javax.swing.JComboBox jComboBox_fonksiyonlar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaLog;
    private javax.swing.JLabel jlabel_FonksiyonSec;
    private javax.swing.JLabel jlabel_secilen_dosya_adi;
    // End of variables declaration//GEN-END:variables
}
